import { Block, View, Text } from '@tarojs/components'
import Taro from '@tarojs/taro'
import withWeapp from '@tarojs/with-weapp'
const app = Taro.getApp()

@withWeapp('Page')
class _C extends Taro.Component {
  state = {
    ColorList: app.globalData.ColorList
  }
  config = {}

  render() {
    const { ColorList: ColorList } = this.state
    return (
      <Block>
        <CuCustom
          bgColor="bg-gradual-blue"
          isBack={true}
          renderBackText={
            <Block>
              <View>返回</View>
            </Block>
          }
          renderContent={
            <Block>
              <View>背景颜色</View>
            </Block>
          }
        />
        <View className="cu-bar bg-white solid-bottom">
          <View className="action">
            <Text className="icon-title text-blue" />深色背景
          </View>
        </View>
        <View className="grid col-3 padding-sm">
          {ColorList.map((item, index) => {
            return (
              <View className="padding-sm" key>
                <View
                  className={
                    'bg-' +
                    item.name +
                    ' padding radius text-center shadow-blur'
                  }
                >
                  <View className="text-lg">{item.title}</View>
                  <View className="margin-top-sm text-Abc">{item.name}</View>
                </View>
              </View>
            )
          })}
        </View>
        <View className="cu-bar bg-white solid-bottom">
          <View className="action">
            <Text className="icon-title text-blue" />淡色背景
          </View>
        </View>
        <View className="grid col-3 bg-white padding-sm">
          {index < 12 && (
            <Block>
              {ColorList.map((item, index) => {
                return (
                  <View className="padding-sm" key>
                    <View
                      className={
                        'bg-' + item.name + ' padding radius text-center light'
                      }
                    >
                      <View className="text-lg">{item.title}</View>
                      <View className="margin-top-sm text-Abc">
                        {item.name}
                      </View>
                    </View>
                  </View>
                )
              })}
            </Block>
          )}
        </View>
        <View className="cu-bar bg-white solid-bottom margin-top">
          <View className="action">
            <Text className="icon-title text-blue" />渐变背景
          </View>
        </View>
        <View className="grid col-2 padding-sm">
          <View className="padding-sm">
            <View className="bg-gradual-red padding radius text-center shadow-blur">
              <View className="text-lg">魅红</View>
              <View className="margin-top-sm text-Abc">#f43f3b - #ec008c</View>
            </View>
          </View>
          <View className="padding-sm">
            <View className="bg-gradual-orange padding radius text-center shadow-blur">
              <View className="text-lg">鎏金</View>
              <View className="margin-top-sm text-Abc">#ff9700 - #ed1c24</View>
            </View>
          </View>
          <View className="padding-sm">
            <View className="bg-gradual-green padding radius text-center shadow-blur">
              <View className="text-lg">翠柳</View>
              <View className="margin-top-sm text-Abc">#39b54a - #8dc63f</View>
            </View>
          </View>
          <View className="padding-sm">
            <View className="bg-gradual-blue padding radius text-center shadow-blur">
              <View className="text-lg">靛青</View>
              <View className="margin-top-sm text-Abc">#0081ff - #1cbbb4</View>
            </View>
          </View>
          <View className="padding-sm">
            <View className="bg-gradual-purple padding radius text-center shadow-blur">
              <View className="text-lg">惑紫</View>
              <View className="margin-top-sm text-Abc">#9000ff - #5e00ff</View>
            </View>
          </View>
          <View className="padding-sm">
            <View className="bg-gradual-pink padding radius text-center shadow-blur">
              <View className="text-lg">霞彩</View>
              <View className="margin-top-sm text-Abc">#ec008c - #6739b6</View>
            </View>
          </View>
        </View>
        <View className="cu-bar bg-white margin-top">
          <View className="action">
            <Text className="icon-title text-blue" />图片背景
          </View>
        </View>
        <View
          className="bg-img bg-mask padding-tb-xl"
          style="background-image: url('https://ossweb-img.qq.com/images/lol/web201310/skin/big10006.jpg');height: 414rpx;"
        >
          <View className="padding-xl text-white">
            <View className="padding-xs text-xl">钢铁之翼</View>
            <View className="padding-xs">Only the guilty need fear me.</View>
          </View>
        </View>
        {/*  <view class="cu-bar bg-white margin-top">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <view class="action">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <text class="icon-title text-blue"></text>视频背景
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </view>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </view>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <view class="bg-video bg-mask flex align-center" style="height: 422rpx;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <video src="https://yz.lol.qq.com/v1/assets/videos/aatrox-splashvideo.webm" autoplay loop muted show-play-btn="{{false}}" controls="{{false}}" objectFit="cover"></video>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <cover-view class="padding-xl text-white ">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <cover-view class="padding-xs  text-xxl text-bold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        暗裔剑魔
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </cover-view>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <cover-view class="padding-xs">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        我必须连同希望一起毁坏……
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </cover-view>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </cover-view>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </view>  */}
        <View className="cu-bar bg-white margin-top">
          <View className="action">
            <Text className="icon-title text-blue" />透明背景(文字层)
          </View>
        </View>
        <View className="grid col-2">
          <View
            className="bg-img padding-bottom-xl"
            style="background-image: url('https://ossweb-img.qq.com/images/lol/web201310/skin/big10007.jpg');height: 207rpx;"
          >
            <View className="bg-shadeTop padding padding-bottom-xl">
              上面开始
            </View>
          </View>
          <View
            className="bg-img padding-top-xl flex align-end"
            style="background-image: url('https://ossweb-img.qq.com/images/lol/web201310/skin/big10001.jpg');height: 207rpx;"
          >
            <View className="bg-shadeBottom padding padding-top-xl flex-sub">
              下面开始
            </View>
          </View>
        </View>
      </Block>
    )
  }
}

export default _C
